oneBotApi:
  send_private_msg: http://localhost:3000/send_private_msg
  send_group_msg: http://localhost:3000/send_group_msg
  get_friend_msg_history: http://localhost:3000/get_friend_msg_history

openai:
  api_key: YOUR_API_KEY
  base_url: https://api.deepseek.com
  module: deepseek-chat

users:
  - qq: SELF_QQ
    name: SELF_NICK_NAME
  - qq: TARGET_QQ
    name: TARGET_NICKNAME
    prompt: TARGET_PROMPT